i did it again
SOMEWANTTOSMILE/Homework_TSM pull request #2
Opened 2023-12-01 21:00 UTC by SOMEWANTTOSMILE

2023-12-01 21:06 UTC, Misnad commented
What have you done again? Please.

2023-12-02 16:06 UTC, nicilytop-tms requested changes
check coments please and do another commit..

2023-12-02 16:06 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +        super().move()
Nope.. voice and move it is different methods.. why are you calling move from voice?

2023-12-02 16:06 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +        super().move()
also here..

2023-12-02 16:06 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +        self.status = status
Where we creating car - we cant define its status.. It looks like I can launch my car without `launch` method
It is bad.. 🤨

2023-12-02 16:06 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +    def __init__(self, status="non launch"):
it is not recomending define strings variables like that..
Better to use None by default and define it below using `if` operator

2023-12-02 16:06 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +    def __init__(self, status="non launch"):
But see comment below

2023-12-03 09:51 UTC, nicilytop-tms requested changes
do it again please

2023-12-03 09:51 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +            'Define voice in %s.' % self.__class__.__name__)
lets move last bracket below

2023-12-03 09:51 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +            'Define voice in %s.' % self.__class__.__name__)
and here

2023-12-03 09:51 UTC, nicilytop-tms commented on Animals_class/Animal_class.py
> +        elif self.status is not None:
we don't need this check.. it looks like if I want mute my car and status is `non launch` I will set status `non launch` contrary to that this status already setted

2023-12-04 15:35 UTC, nicilytop-tms approved these changes
ok ok

2023-12-04 15:37 UTC, merged